ALTER TABLE user ADD COLUMN tenant_id VARCHAR(100) NOT NULL;

ALTER TABLE author ADD COLUMN tenant_id VARCHAR(100) NOT NULL;

ALTER TABLE announcement ADD COLUMN tenant_id VARCHAR(100) NOT NULL;

ALTER TABLE book ADD COLUMN tenant_id VARCHAR(100) NOT NULL;

ALTER TABLE category ADD COLUMN tenant_id VARCHAR(100) NOT NULL;

ALTER TABLE event ADD COLUMN tenant_id VARCHAR(100) NOT NULL;

ALTER TABLE fine ADD COLUMN tenant_id VARCHAR(100) NOT NULL;

ALTER TABLE inventory ADD COLUMN tenant_id VARCHAR(100) NOT NULL;

ALTER TABLE library_branch ADD COLUMN tenant_id VARCHAR(100) NOT NULL;

ALTER TABLE library_card ADD COLUMN tenant_id VARCHAR(100) NOT NULL;

ALTER TABLE loan_history ADD COLUMN tenant_id VARCHAR(100) NOT NULL;

ALTER TABLE membership ADD COLUMN tenant_id VARCHAR(100) NOT NULL;

ALTER TABLE notification ADD COLUMN tenant_id VARCHAR(100) NOT NULL;

ALTER TABLE publisher ADD COLUMN tenant_id VARCHAR(100) NOT NULL;

ALTER TABLE reservation ADD COLUMN tenant_id VARCHAR(100) NOT NULL;

ALTER TABLE review ADD COLUMN tenant_id VARCHAR(100) NOT NULL;

ALTER TABLE shelf ADD COLUMN tenant_id VARCHAR(100) NOT NULL;
